# Generated by Django 2.2.4 on 2019-09-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
    ]
